### ISSUE TITLE
 error  while rake rails:upgrade:routes --trace

### ISSUE THREAD

**Issue by gudata** [jm/rails_upgrade#3]
Hi,
I am with Rails '2.3.5' 
I have done.

script/plugin install --force git://github.com/rails/rails_upgrade.git

then 

rake rails:upgrade:routes --trace
(in /home/guda/re)
*\* Invoke rails:upgrade:routes (first_time)
*\* Execute rails:upgrade:routes
rake aborted!
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `load_missing_constant': uninitialized constant Rails::Upgrading::FakeRouter::Translate
/home/guda/re/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:47:in`upgrade_routes'
/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in `const_missing'
(eval):4:in`upgrade_routes'
/home/guda/re/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:18:in `draw'
(eval):1:in`upgrade_routes'
/home/guda/re/vendor/plugins/rails_upgrade/lib/tasks/../../lib/routes_upgrader.rb:28:in `generate_new_routes'
/home/guda/re/vendor/plugins/rails_upgrade/lib/tasks/rails_upgrade_tasks.rake:28
/usr/lib/ruby/1.8/rake.rb:636:in`call'
/usr/lib/ruby/1.8/rake.rb:636:in `execute_without_benchmark'
/usr/lib/ruby/1.8/rake.rb:631:in`each'
/usr/lib/ruby/1.8/rake.rb:631:in `execute_without_benchmark'
./lib/tasks/task_benchmark.rb:4:in`execute'
/usr/lib/ruby/1.8/benchmark.rb:293:in `measure'
./lib/tasks/task_benchmark.rb:3:in`execute'
/usr/lib/ruby/1.8/rake.rb:597:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/monitor.rb:242:in`synchronize'
/usr/lib/ruby/1.8/rake.rb:590:in `invoke_with_call_chain'
/usr/lib/ruby/1.8/rake.rb:583:in`invoke'
/usr/lib/ruby/1.8/rake.rb:2051:in `invoke_task'
/usr/lib/ruby/1.8/rake.rb:2029:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2029:in `each'
/usr/lib/ruby/1.8/rake.rb:2029:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:2023:in`top_level'
/usr/lib/ruby/1.8/rake.rb:2001:in `run'
/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:28

here is my routes.rb
https://gist.github.com/4a6ecf36e517b0c6e77e

**Comment by greboide** [comment]
hi, just update your rails gem to version 2.3.8 before trying to migrate and comment RAILS_GEM_VERSION out on config/environment.rb

**Comment by gudata** [comment]
Thanks! Will try it.

**Comment by greboide** [comment]
in fact it didnt worked :S

**Comment by gudata** [comment]
for me also

**Comment by gudata** [comment]
I found the problem - it was the 

Translate::Routes.translation_ui(map) if RAILS_ENV != "production"

line from 
http://github.com/newsdesk/translate
